//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnabiaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceMonth { get; set; }
        public string InvoiceDate { get; set; }
        public string DueDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> InvoiceGenerateBy { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
    
        public virtual InvoiceType InvoiceType1 { get; set; }
        public virtual PaymentMethod PaymentMethod1 { get; set; }
        public virtual Store Store { get; set; }
    }
}
