//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnabiaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreWeb
    {
        public int StoreWebID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string StoreBanner1 { get; set; }
        public string StoreBanner2 { get; set; }
        public string StoreBanner3 { get; set; }
        public string CreationDate { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
