//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnabiaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Invoices = new HashSet<Invoice>();
            this.InvoicePaymentReceipts = new HashSet<InvoicePaymentReceipt>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Orders = new HashSet<Order>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.ProductImages = new HashSet<ProductImage>();
            this.Products = new HashSet<Product>();
            this.StoreWebs = new HashSet<StoreWeb>();
        }
    
        public int StoreID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string BusinessName { get; set; }
        public string BusinessAddress { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public string EmailID { get; set; }
        public string CnicHolderName { get; set; }
        public string CnicNumber { get; set; }
        public string CnicExpiryDate { get; set; }
        public string FrontCopyOfCnic { get; set; }
        public string BackCopyOfCnic { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> Package { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public string RegistrationDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Store_Logo { get; set; }
        public Nullable<int> CityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePaymentReceipt> InvoicePaymentReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Package Package1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreWeb> StoreWebs { get; set; }
    }
}
